version: '3'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src
    environment:
      - BACKEND_URL=https://atacadogames.tk
      - REDIS_URL=redis://cache
      - APIPREFIX=/api/v1
      - NODE_ENV=dev
    links:
      - db
      - redis
    networks:
      - backend
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - backend
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - ./db/redis-data:/data
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  mongodata:

