const swaggerUi = require('swagger-ui-express')
const swaggerJsDoc = require('swagger-jsdoc')

const options = {
  swaggerDefinition: {
    info: {
      title: 'Marketplace',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc'
    }
  },
  apis: ['routes.js']
}

const specs = swaggerJsDoc(options)

module.exports = app => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs))
}
